<?php


namespace App\Repositories;

use App\Contact;
use App\Room;

class RoomRepository extends Repository
{
    public function __construct(Room $room)
    {
        $this->model = $room;
    }

    public function get($select = '*', $take = false, $where = false, $paginate = false, $where2 = false)
    {
        $room = parent::get($select, $take, $where, $paginate); // TODO: Change the autogenerated stub

        if ($where2 && is_array($where2) && count($where2) > 2) {
            $rooms = $this->model->select($select)->where($where2[0], $where2[1], $where2[2])->get();
            $rooms->load('checks');
            $rooms->load('counts');
            return $rooms;
        }
        elseif ($where2) {
            $rooms = $this->model->select($select)->where($where2[0], $where2[1])->get();
            $rooms->load('checks');
            $rooms->load('counts');
            return $rooms;
        }

        return $room;
    }
}
